create table users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null unique,
    password_hash varchar(255) not null,
    full_name varchar(120) not null,
    created_at timestamp with time zone not null default current_timestamp
);

create table portfolios (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id),
    name varchar(120) not null,
    base_currency varchar(3) not null,
    created_at timestamp with time zone not null default current_timestamp
);

create table holdings (
    id bigint generated by default as identity primary key,
    portfolio_id bigint not null references portfolios(id),
    symbol varchar(20) not null,
    asset_type varchar(20) not null,
    quantity numeric(19, 4) not null,
    average_cost numeric(19, 4) not null,
    currency varchar(3) not null,
    created_at timestamp with time zone not null default current_timestamp
);

create table transactions (
    id bigint generated by default as identity primary key,
    holding_id bigint not null references holdings(id),
    type varchar(20) not null,
    quantity numeric(19, 4) not null,
    price numeric(19, 4) not null,
    trade_date date not null,
    created_at timestamp with time zone not null default current_timestamp
);

create index idx_portfolios_user_id on portfolios(user_id);
create index idx_holdings_portfolio_id on holdings(portfolio_id);
create index idx_transactions_holding_id on transactions(holding_id);
