spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/assetflow
    username: assetflow
    password: assetflow
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 8080
